### ISSUE TITLE
moment.js development is stale

### ISSUE THREAD

**Issue by zinen** [samuelmr/nordpool-node#7]
As stated in the [project status](https://momentjs.com/docs/#/-project-status/) of moment.js documentation further development are stopped and the teams itself says:

> we would like to discourage Moment from being used in new projects going forward

The moment.js links to `dayjs` as the [smallest alternative](https://momentjs.com/docs/#/-project-status/recommendations/) to be a applicable successor.

@samuelmr would you consider a pull request with `moment` replaced by `dayjs`?

**Comment by samuelmr** [comment]
Yes, I would highly appreciate that PR.

**Comment by zinen** [comment]
Sweet. I'll look into it. Do note that the returned data no longer will be a [moment object](https://github.com/samuelmr/nordpool-node/blob/64e4d4f947e01c44553b2ad0a1639405b0855e50/lib/prices.js#L102). I recommend returning a native js date object instead. API users may not even have to adopt anything as moment handles parsing the native js date object just fine.

I know that the native js date object is basically a UTC timestamp but many other npm packages has evolved around the UTC as the date object has been improved at lot the last few years in js.

The native js date is already supported by most browsers to show correctly depending on locale settings in browsers or computer/server.

**Comment by samuelmr** [comment]
Using a native Date is OK.

Note that you have to convert e.g. `date.get('dayOfYear') == opts.date.get('dayOfYear')` (in [prices.js](https://github.com/samuelmr/nordpool-node/blob/64e4d4f947e01c44553b2ad0a1639405b0855e50/lib/prices.js#L21)) and other internal functionality that assumes moment.js into something that works with native Date objects.

Also examples need to be updated. Perhaps they could use day.js for easy formatting?

Please update the version number to 2.* in the package.json since not returning a moment.js object will break backward compatibility.

**Comment by zinen** [comment]
A bit later I've come pretty far. Code can be seen here https://github.com/zinen/nordpool-node/tree/replace-moment-with-day.js.

But as the returned object will no longer be a moment object I would suggest this to be a major change and so bump to v3*.

Upgrading to day.js will reduce install size from `v2.1.0`=5.34 MB to 715 KB. That's a lot of unused code in moment.

Support for node is changed to >8 insted of the current >7. And so i added #11  to make it still work on node v7.

**Comment by samuelmr** [comment]
Yes, I was also suggesting a major version change but mistyped 2.* (meant 3.*).

I don't actually think we need to worry about old node versions. It may be beneficial to indicate which node versions can run `nordpool-node` but if something doesn't work in older versions it's probably not worth the effort to create workarounds.

While we're making a major version update, we could also change the `callback` type functions to `async`s.
Instead of 
```js
Prices.prototype.yearly = function (opts, callback) {
  opts.url = config.priceUrlYearly
  this.getValues(opts, callback)
}
```
we would have
```js
Prices.prototype.yearly = async (opts, callback) => {
  opts.url = config.priceUrlYearly
  return await getValues(opts)
}
```

I took a look at your branch. Looks good to me.

In the README.md, you could perhaps refer to https://www.ecma-international.org/ecma-262/11.0/#sec-date-time-string-format instead of w3schools.

**Comment by zinen** [comment]
Very much like the idea of changing from callback to the newer async/await method (it tends to look much cleaner). I'll do some changes and get back to you.

Then you could run

```js
console.log(await prices.at(opts))
```
Instead of 

```js
prices.at(opts, function (error, results) {
  if (error) { throw error }
  console.log(results)
})
```

Will also update the README.md with new link and also new examples is needed to support this change to async/await.
